### ISSUE TITLE
Runner should add 'HasBinding' expectation to subject

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#32]
To have backwards compatibility with the existing exercises the runner should add 'HasBinding'  (Declares in v2) expectation to the subject of the test.

**Comment by flbulgarelli** [comment]
@rodri042 do you have any clue about how to achieve this?

**Comment by rodri042** [comment]
It already supports it. See this test: https://github.com/mumuki/mumuki-gobstones-runner/blob/master/spec/integration_spec.rb#L112

I think that **mumukit-inspection** is doing the conversion.

**Comment by flbulgarelli** [comment]
Hi @rodri042! 

The issue here is that such expectation should be generated automatically. In the given example (https://github.com/mumuki/mumuki-gobstones-runner/blob/master/spec/integration_spec.rb#L112) the expectation was added explicitly, but if you remove that line the test won't pass - but it should!

**Comment by rodri042** [comment]
In that case we could override this method (https://github.com/mumuki/mumukit/blob/5db86b68e8509bcfa4a5bb030f8a68509e9da065/lib/mumukit/templates/mulang_expectations_hook.rb#L53) in the expectations_hook. If the request has subject, we add the new expectation.
