### ISSUE TITLE
error:  wrong_arguments_quantity is being ignored

### ISSUE THREAD

**Issue by luchotc** [mumuki/mumuki-gobstones-runner#37]
### Example

{
		"content" : "program{ \nDibujarLinea3(Verde)\n}",
		"test" : "check_head_position: true\n\nexamples:\n - title: '¡BOOM!'\n   initial_board: |\n     GBB/1.0\n     size 3 3\n     head 0 0\n   error: wrong_arguments_quantity",
		"expectations" : [ ],
		"extra" : "procedure DibujarLinea3(color, direccion) {\n  Poner(color)\n  Mover(direccion)\n  Poner(color)\n  Mover(direccion)\n  Poner(color)\n}",
		"language" : "gobstones"
}

### Result

The variable output in this line: https://github.com/mumuki/mumuki-gobstones-runner/blob/master/lib/expectations_hook.rb#L9 has this value: `{"exit":"errored","out":"<pre>[2:1]: El procedimiento \"DibujarLinea3\" espera recibir 2 parámetros pero se lo invoca con un argumento.</pre>"}`

**Comment by rodri042** [comment]
Ok, so that compilation errors should be ignored here (https://github.com/mumuki/mumuki-gobstones-runner/blob/359c14257dcb664266f61938bc7aab78a377d79b/lib/multiple_executions_runner.rb#L3) and then add assertions into Checker (https://github.com/mumuki/mumuki-gobstones-runner/blob/359c14257dcb664266f61938bc7aab78a377d79b/lib/checker.rb)
