### ISSUE TITLE
Boards should be more accessible

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#57]
The gs-board should provide an alt-text for visually impaired users. Using the plain GBB as plain alt-text is enough - we have validated it with an user.

**Comment by flbulgarelli** [comment]
This probably requires modifying `gs-board` component

**Comment by rodri042** [comment]
Added to `gobstones-board`'s 1.8.14.

![screenshot1](https://user-images.githubusercontent.com/1631752/36563333-7536fb02-1822-11e8-8693-a3a6c3a9eb00.png)

Please test if it works OK with the screen reader

**Comment by flbulgarelli** [comment]
@julian-berbel please update the runner and test it locally using an screen reader

**Comment by julian-berbel** [comment]
The aria-hidden tag seems to actually make it so the screen reader will ignore the table entirely, so the aria-label is not read.

Removing that property also made Orca start reading the column numbers instead of the label.

I'm currently trying different alternatives to get this to work.
So far I've tried, and hasn't worked:
* adding a <p> element with hidden property - Screen readers ignore html hidden things too
* moving the aria-hidden to the tbody below - For some reason it again starts reading column numbers
* moving the aria-label to other non-hidden elements near the table - Screen reader still ignores it

**Comment by rodri042** [comment]
What about a "visible" element with opacity: 0 or just an empty tag with
aria-label?

On Feb 28, 2018 12:51 PM, "Julián Berbel Alt" <notifications@github.com>
wrote:

The aria-hidden tag seems to actually make it so the screen reader will
ignore the table entirely, so the aria-label is not read.

Removing that property also made Orca start reading the column numbers
instead of the label.

I'm currently trying different alternatives to get this to work.
So far I've tried, and hasn't worked:

   - adding a

   element with hidden property - Screen readers ignore html hidden things
   too
   - moving the aria-hidden to the tbody below - For some reason it again
   starts reading column numbers
   - moving the aria-label to other non-hidden elements near the table -
   Screen reader still ignores it

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mumuki/mumuki-gobstones-runner/issues/57#issuecomment-369281400>,
or mute the thread

**Comment by julian-berbel** [comment]
can't speak for all screen readers but orca seems to read aria-labels on only a select few elements such as `<button>`s.

Adding an element with opacity 0 does seem to work, though we'd have to make it so it doesn't push down the other elements.

**Comment by flbulgarelli** [comment]
Antes updates on this?
